volumes:
  data:

services:
  server:
    build:
      context: ../dist
      dockerfile: ./Containerfile
    restart: unless-stopped
    volumes:
      - data:/server/data
    ports:
      - 8080:8080
