default:
  image: ubuntu:25.10

stages:
  - .pre
  - build
  - lint
  - release

variables:
  CONTAINER_CI_IMAGE: $CI_REGISTRY/theo/simple-video-cms/ci:latest
  CONTAINER_TEST_BACK_IMAGE: $CI_REGISTRY/theo/simple-video-cms:back-$CI_COMMIT_REF_SLUG
  CONTAINER_TEST_FRONT_IMAGE: $CI_REGISTRY/theo/simple-video-cms:front-$CI_COMMIT_REF_SLUG
  CONTAINER_RELEASE_BACK_IMAGE: $CI_REGISTRY/theo/simple-video-cms:back-latest
  CONTAINER_RELEASE_FRONT_IMAGE: $CI_REGISTRY/theo/simple-video-cms:front-latest

.merge-rules:
  rules:
    - if: $CI_PIPELINE_SOURCE == 'merge_request_event'

.deploy-rules:
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH

include:
  - local: /.gitlab-ci/build.yml
  - local: /.gitlab-ci/docker.yml
  - local: /.gitlab-ci/lint.yml

build ci image:
  stage: .pre
  extends:
    - .docker-job
  script:
    - docker build -f docker/ci.containerfile -t $CONTAINER_CI_IMAGE .
    - docker push $CONTAINER_CI_IMAGE
  rules:
    - changes:
        - docker/ci.containerfile
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH

build vcpkg deps:
  stage: .pre
  image: $CONTAINER_CI_IMAGE
  dependencies:
    - build ci image
  timeout: 2h
  extends:
    - .install-job
    - .merge-rules
  variables:
    CACHE_POLICY: pull-push
  script:
    - cmake --preset vcpkg

debug build:
  image: $CONTAINER_CI_IMAGE
  extends:
    - .build-job
    - .merge-rules
  variables:
    BUILD: debug

release build:
  image: $CONTAINER_CI_IMAGE
  extends:
    - .build-job
  rules:
    - !reference [.merge-rules, rules]
    - !reference [.deploy-rules, rules]
  variables:
    BUILD: release

docker build:
  stage: build
  extends:
    - .docker-job
  needs:
    - job: release build
      artifacts: true
  rules:
    - !reference [.merge-rules, rules]
    - !reference [.deploy-rules, rules]
  script:
    - docker build -f docker/back.containerfile -t $CONTAINER_TEST_BACK_IMAGE dist
    - docker build -f docker/front.containerfile -t $CONTAINER_TEST_FRONT_IMAGE dist
    - docker push $CONTAINER_TEST_BACK_IMAGE
    - docker push $CONTAINER_TEST_FRONT_IMAGE

lint:
  image: $CONTAINER_CI_IMAGE
  extends:
    - .lint-job
    - .merge-rules

docker release image:
  stage: release
  dependencies: []
  extends:
    - .docker-job
    - .deploy-rules
  script:
    - docker pull $CONTAINER_TEST_BACK_IMAGE
    - docker pull $CONTAINER_TEST_FRONT_IMAGE
    - docker tag $CONTAINER_TEST_BACK_IMAGE $CONTAINER_RELEASE_BACK_IMAGE
    - docker tag $CONTAINER_TEST_FRONT_IMAGE $CONTAINER_RELEASE_FRONT_IMAGE
    - docker push $CONTAINER_RELEASE_BACK_IMAGE
    - docker push $CONTAINER_RELEASE_FRONT_IMAGE
