default:
  image: ubuntu:26.04

stages:
  - .pre
  - build
  - test
  - lint
  - review
  - deploy

variables:
  CONTAINER_BASE_IMAGE: $CI_REGISTRY/theo/simple-video-cms
  CONTAINER_CI_IMAGE: $CONTAINER_BASE_IMAGE/ci:clang-22
  CONTAINER_TEST_IMAGE: $CONTAINER_BASE_IMAGE:$CI_COMMIT_REF_SLUG
  CONTAINER_RELEASE_IMAGE: $CONTAINER_BASE_IMAGE:$CI_COMMIT_SHORT_SHA

.merge-rules:
  rules:
    - if: $CI_PIPELINE_SOURCE == 'merge_request_event'

.deploy-rules:
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH

.deploy-tags:
  tags:
    - linux
    - docker
    - deploy

include:
  - local: /.gitlab-ci/build.yml
  - local: /.gitlab-ci/docker.yml
  - local: /.gitlab-ci/lint.yml
  - local: /.gitlab-ci/test.yml

build ci image:
  stage: .pre
  extends:
    - .docker-job
  rules:
    - !reference [.merge-rules, rules]
    - !reference [.deploy-rules, rules]
  script:
    - docker build -f container/ci.containerfile -t $CONTAINER_CI_IMAGE .
    - docker push $CONTAINER_CI_IMAGE

debug build:
  image: $CONTAINER_CI_IMAGE
  extends:
    - .build-job
    - .merge-rules
  variables:
    BUILD: debug
    BUILD_TESTS: ON
    BUILD_COVERAGE: ON
    BUILD_TARGETS: back back_tests common_tests
  artifacts:
    expire_in: 3 days
    name: debug
    paths:
      - build/vcpkg/Debug/back
      - build/vcpkg/Debug/back_tests
      - build/vcpkg/Debug/common_tests
      - build/vcpkg/**/*.gcda
      - build/vcpkg/**/*.gcno

release build:
  image: $CONTAINER_CI_IMAGE
  extends:
    - .build-job
  rules:
    - !reference [.merge-rules, rules]
    - !reference [.deploy-rules, rules]
  variables:
    BUILD: release
  artifacts:
    expire_in: 3 days
    name: dist
    paths:
      - dist

docker build:
  stage: build
  extends:
    - .docker-job
  needs:
    - job: release build
      artifacts: true
  rules:
    - !reference [.merge-rules, rules]
    - !reference [.deploy-rules, rules]
  script:
    - docker build -f container/Containerfile -t $CONTAINER_TEST_IMAGE dist
    - docker push $CONTAINER_TEST_IMAGE

lint:
  image: $CONTAINER_CI_IMAGE
  extends:
    - .lint-job
    - .merge-rules

deploy review:
  stage: review
  extends:
    - .merge-rules
    - .docker-job
  variables:
    GIT_STRATEGY: none
    CONTAINER_NAME: review-$CI_COMMIT_REF_SLUG
  before_script:
    - !reference [.docker-job, before_script]
    - apk add --no-cache curl
  script:
    - docker pull $CONTAINER_TEST_IMAGE
    - docker rm -f "$CONTAINER_NAME" || true
    - docker run -d --name "$CONTAINER_NAME" -P $CONTAINER_TEST_IMAGE
    - 'export PORT=$(docker port "$CONTAINER_NAME" 8080/tcp | cut -d: -f2)'
    - export HOST=$(curl -4 ifconfig.me)
    - echo "Deployed on http://$HOST:$PORT"
  environment:
    name: review/$CI_COMMIT_REF_NAME
    url: http://$HOST:$PORT
    on_stop: stop review
    auto_stop_in: 1 week

stop review:
  stage: review
  when: manual
  extends:
    - .merge-rules
    - .docker-job
  variables:
    GIT_STRATEGY: none
    CONTAINER_NAME: review-$CI_COMMIT_REF_SLUG
  script:
    - docker rm -f "$CONTAINER_NAME" || true
  environment:
    name: review/$CI_COMMIT_REF_NAME
    action: stop

docker release image:
  stage: deploy
  dependencies: []
  extends:
    - .docker-job
    - .deploy-rules
  variables:
    GIT_STRATEGY: none
  script:
    - docker pull $CONTAINER_TEST_IMAGE
    - docker tag $CONTAINER_TEST_IMAGE $CONTAINER_RELEASE_IMAGE
    - docker tag $CONTAINER_TEST_IMAGE $CONTAINER_BASE_IMAGE:latest
    - docker push $CONTAINER_RELEASE_IMAGE
    - docker push $CONTAINER_BASE_IMAGE:latest

deploy preprod:
  stage: deploy
  extends:
    - .docker-job
    - .deploy-rules
    - .deploy-tags
  dependencies:
    - docker release image
  variables:
    GIT_STRATEGY: none
  script:
    - git clone https://gitlab-ci-token:${CI_JOB_TOKEN}@gitlab.devau.co/theo/simple-video-cms-vietvodao-configuration.git deploy-configs
    - cd deploy-configs
    - docker compose -p simple_video_cms_dev -f compose-dev.yml pull
    - docker compose -p simple_video_cms_dev -f compose-dev.yml up -d --force-recreate
  environment:
    name: pre-production

deploy production:
  stage: deploy
  extends:
    - .docker-job
    - .deploy-tags
  rules:
    - if: '$CI_COMMIT_TAG'
      when: manual
  variables:
    GIT_STRATEGY: none
  script:
    - git clone https://gitlab-ci-token:${CI_JOB_TOKEN}@gitlab.devau.co/theo/simple-video-cms-vietvodao-configuration.git deploy-configs
    - cd deploy-configs
    - export IMAGE_TAG=$CI_COMMIT_TAG
    - docker pull $CONTAINER_RELEASE_IMAGE
    - docker tag $CONTAINER_RELEASE_IMAGE $CONTAINER_BASE_IMAGE:$IMAGE_TAG
    - docker compose -p simple_video_cms_prod -f compose-prod.yml up -d
    - docker push $CONTAINER_BASE_IMAGE:$IMAGE_TAG
  environment:
    name: production
