services:

  builder:
    image: alpine-builder
    build:
      context: ./builder
      dockerfile: Containerfile
    command: /bin/true

  front:
    build:
      context: ./front
      dockerfile: Containerfile
    environment:
      SERVER_URL: back:5000
    ports:
      - 8080:8080
    depends_on:
      - builder
      - back

  back:
    build:
      context: ./back
      dockerfile: Containerfile
    volumes:
      - ./back/data:/data
      - ./back/static:/static
      - ./back/templates:/templates
    depends_on:
      - builder
