volumes:
  data:

services:
  server:
    build:
      context: dist
      dockerfile: ../docker/Containerfile
    restart: unless-stopped
    volumes:
      - data:/data
    ports:
      - 8080:8080
