include:
  - local: /.gitlab-ci/common.yml

.analyze:
  stage: analyze
  extends:
    - .base-job
  before_script:
    - !reference [.base-job, before_script]
    - apt-get -y install clang-tidy-21
  script:
    - !reference [.base-job, script]
    - make analyze-${TARGET} -j

.back-analyze:
  extends:
    - .analyze
    - .back-base-job
  before_script:
    - !reference [.back-base-job, before_script]
    - !reference [.analyze, before_script]
  script:
    - !reference [.back-base-job, script]
    - !reference [.analyze, script]
