include:
  - local: /.gitlab-ci/common.yml

.build-job:
  stage: build
  extends:
    - .install-job
  script:
    - cmake --preset vcpkg -DCMAKE_INSTALL_PREFIX=dist
    - cmake --build --preset vcpkg-${BUILD} --parallel --target install
  artifacts:
    expire_in: 3 days
    name: dist
    paths:
      - dist
