include:
  - local: /.gitlab-ci/common.yml

variables:
  BUILD_CACHE_PATH: build/${BUILD}/${TARGET}/**/*

.local-build:
  stage: build
  extends:
    - .base-job
  script:
    - make DEBUG=${DEBUG} ${TARGET} -j
  artifacts:
    paths:
      - bin/${BUILD}/${TARGET}
  cache:
    paths:
      - $BUILD_CACHE_PATH

.back-local-build:
  extends:
    - .local-build
    - .back-base-job
  script:
    - !reference [.back-base-job, script]
    - !reference [.local-build, script]
  cache:
    paths:
      - $BUILD_CACHE_PATH
      - common/third-party/ffmpeg/**/*
      - common/third-party/libpng/**/*
      - common/third-party/zlib/**/*
