.base-tag:
  tags:
    - linux
    - docker

.base-job:
  extends:
    - .base-tag
  before_script:
    - apt-get update
    - apt-get -y install make clang-21
  script:
    - ./configure --zlib

.back-base-job:
  before_script:
    - !reference [.base-job, before_script]
    - apt-get -y install nasm
  script:
    - !reference [.base-job, script]
    - make -C back zlib -j
    - ./configure --libpng --ffmpeg
  tags: !reference [.base-job, tags]
