.dev-tags:
  tags:
    - linux
    - docker
    - dev

.vcpkg-install-job:
  extends:
    - .dev-tags
  variables:
    NUGET_FEED: ${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/packages/nuget/index.json
    VCPKG_NUGET_REPO: vcpkg-packages
    VCPKG_ROOT: ${CI_PROJECT_DIR}/vcpkg
    VCPKG_BINARY_SOURCES: clear;nuget,${VCPKG_NUGET_REPO},readwrite
  before_script:
    - git clone https://github.com/microsoft/vcpkg.git ${VCPKG_ROOT}
    - ${VCPKG_ROOT}/bootstrap-vcpkg.sh -disableMetrics
    - NUGET_EXE="$(${VCPKG_ROOT}/vcpkg fetch nuget | tail -n 1)"
    - mono ${NUGET_EXE} source add -Name ${VCPKG_NUGET_REPO} -Source ${NUGET_FEED} -UserName gitlab-ci-token -Password ${CI_JOB_TOKEN} -StorePasswordInClearText -NonInteractive
    - mono ${NUGET_EXE} setapikey ${CI_JOB_TOKEN} -Source ${VCPKG_NUGET_REPO} -NonInteractive

.install-job:
  extends:
    - .vcpkg-install-job
  before_script:
    - !reference [.vcpkg-install-job, before_script]
    - npm ci
