include:
  - local: /.gitlab-ci/common.yml

.lint-job:
  stage: lint
  dependencies: []
  extends:
    - .install-job
  script:
    - cmake --preset lint
    - cmake --build build/lint --parallel 1
    - npx eslint "front/**/*.js"
