include:
  - local: /.gitlab-ci/common.yml

.lint-job:
  stage: lint
  extends:
    - .install-job

back lint:
  image: $CONTAINER_CI_IMAGE
  extends:
    - .lint-job
    - .merge-rules
  script:
    - cmake --preset lint
    - cmake --build build/lint --parallel 1

front lint:
  image: $CONTAINER_CI_IMAGE
  extends:
    - .lint-job
    - .merge-rules
  script:
    - npx eslint "front/**/*.js"
