FROM alpine-builder AS builder

RUN apk add --no-cache \
        mariadb-connector-c-dev

ADD *.h *.cpp /sources/

RUN make -C /sources -j -k server LDFLAGS="-lmysqlclient -lz -lzstd -lssl -lcrypto -lresolv -lm"

# --------------------------------------------------------------------------------
FROM scratch

COPY --from=builder /sources/server /server

CMD ["/server"]
