FROM alpine-builder AS builder

ADD *.h *.cpp ${SOURCE_DIR}/

#RUN mariadb_config
RUN make -C ${SOURCE_DIR} -j -k server CXXFLAGS="${CXXFLAGS}" && strip ${SOURCE_DIR}/server

# --------------------------------------------------------------------------------
FROM scratch

COPY --from=builder /sources/server /server

CMD ["/server"]
