FROM alpine-builder AS builder

RUN apk add --no-cache \
        mariadb-connector-c-dev

ADD *.h *.cpp ${SOURCE_DIR}/

#RUN mariadb_config
RUN make -C ${SOURCE_DIR} -j -k server \
        CXXFLAGS="${CXXFLAGS} -I/usr/include/mysql -I/usr/include/mysql/mysql" \
        LDFLAGS="-L/usr/lib/ -lmariadb -lz -ldl -lssl -lcrypto"

# --------------------------------------------------------------------------------
FROM scratch

COPY --from=builder /sources/server /server

CMD ["/server"]
