FROM python:3.12

ADD requirements.txt /

RUN pip install --no-cache-dir -r /requirements.txt

RUN apt-get update && apt-get install -y --no-install-recommends  \
        libgl1-mesa-glx \
    && rm -rf /var/lib/apt/lists/*

ADD . /VideoHub

WORKDIR /VideoHub

CMD [ "python", "/VideoHub/server.py" ]
