#include <session.h>

#include <catch2/catch_test_macros.hpp>

#include <thread>

TEST_CASE("Session::create_session")
{
    SECTION("creates valid session bound to user")
    {
        Session session;

        const int user_id{ 42 };
        const std::string session_id{ session.create_session(user_id) };

        REQUIRE_FALSE(session_id.empty());
        REQUIRE(session.user_from_session(session_id) == user_id);
    }

    SECTION("expires session after max age")
    {
        Session session;

        using namespace std::chrono_literals;
        const auto max_age{ std::chrono::duration_cast<std::chrono::seconds>(1ms) };
        const std::string session_id{ session.create_session(42, max_age) };
        std::this_thread::sleep_for(10ms);

        session.create_session(100); // trigger cleanup of expired sessions

        REQUIRE(session.user_from_session(session_id) == Session::invalid_user_id());
    }
}

TEST_CASE("Session::insert_session_id_to_cookie")
{
    SECTION("returns cookie header for existing session")
    {
        Session session;
        const std::string session_id{ session.create_session(7) };

        const std::string cookie{ session.insert_session_id_to_cookie(session_id) };

        REQUIRE_FALSE(cookie.empty());
        REQUIRE(cookie.find(session_id) != std::string::npos);
        REQUIRE(cookie.find("HttpOnly") != std::string::npos);
    }

    SECTION("returns empty string for unknown session")
    {
        Session session;

        REQUIRE(session.insert_session_id_to_cookie("missing-session").empty());
    }
}

TEST_CASE("Session::extract_session_id_from_cookie")
{
    SECTION("extracts id from cookie generated by session")
    {
        Session session;
        const std::string session_id{ session.create_session(9) };
        const std::string cookie{ session.insert_session_id_to_cookie(session_id) };

        REQUIRE(Session::extract_session_id_from_cookie(cookie) == session_id);
    }
}

TEST_CASE("Session::remove_session_reset_cookie")
{
    SECTION("removes session and returns reset cookie")
    {
        Session session;
        const std::string session_id{ session.create_session(12) };

        const std::string reset_cookie{ session.remove_session_reset_cookie(session_id) };

        REQUIRE(session.user_from_session(session_id) == Session::invalid_user_id());
        REQUIRE(reset_cookie.find("Max-Age=0") != std::string::npos);
    }
}
