FROM alpine-builder AS builder

ADD main.cpp /sources/

WORKDIR /build

RUN g++ -std=c++23 -static -o server -O2 -I/sources -DCPPHTTPLIB_USE_POLL /sources/main.cpp \
        && strip server

# --------------------------------------------------------------------------------
FROM scratch

COPY --from=builder /build/server /server

EXPOSE 80

CMD ["/server"]
