FROM alpine-builder AS builder

ADD *.h *.cpp ${SOURCE_DIR}/

RUN make -C ${SOURCE_DIR} -j -k server CXXFLAGS="${CXXFLAGS}" LDFLAGS="${LDFLAGS}"

# --------------------------------------------------------------------------------
FROM scratch

COPY --from=builder /sources/server /server

#RUN ldd /server or /sources/server in alpine image
COPY --from=builder /usr/lib/libstdc++* /usr/lib/libgcc* /usr/lib/
COPY --from=builder /lib/ld-musl* /lib/

EXPOSE 80

CMD ["/server"]
