FROM alpine-builder AS builder

ADD *.h *.cpp /sources/

RUN make -C /sources -j -k server

# --------------------------------------------------------------------------------
FROM scratch

COPY --from=builder /sources/server /server

EXPOSE 80

CMD ["/server"]
