import { readFileSync, writeFileSync, unlinkSync, renameSync, readdirSync, existsSync } from 'fs';
import { nodeResolve } from '@rollup/plugin-node-resolve';
import commonjs from '@rollup/plugin-commonjs';
import terser from '@rollup/plugin-terser';
import { rollupPluginHTML as html } from '@web/rollup-plugin-html';
import css from 'rollup-plugin-import-css';
import babel from '@rollup/plugin-babel';
import del from 'rollup-plugin-delete';
import { videojsEntries } from './rollup.shared.js';

const SRC_HTML_FILE = 'index.html';
const SRC_HTML = `front/${SRC_HTML_FILE}`;
const PROD_HTML_FILE = 'index-prod.html';
const PROD_HTML = `front/${PROD_HTML_FILE}`;
const DIST_DIR = 'dist';

// prepare index.html without absolute path for html plugin
{
  const src = readFileSync(SRC_HTML, 'utf-8');
  const prod = src
    .replace(/href="\/assets\//g, 'href="./assets/')
    .replace(/src="\/index\.js"/g, 'src="./index.js"')
    .replace(/src="\/env\.js"/g, 'src="./env.js"');
  writeFileSync(PROD_HTML, prod);
}

// env.js is generated by back server if not exists
{
  const content = Math.random().toString(36).substring(2, 10); // generate a random to have a different hash at each build
  writeFileSync('front/env.js', content);
}

function deleteProdHtmlFile() {
  return {
    name: 'delete-prod-html-file',
    closeBundle() {
      unlinkSync(PROD_HTML);
      renameSync(`${DIST_DIR}/${PROD_HTML_FILE}`, `${DIST_DIR}/${SRC_HTML_FILE}`);
    },
  };
}

const terserOptions = {
  ecma: 2020,
  warnings: true,
  compress: { passes: 2 },
};

const withTerser = (entry) => ({
  ...entry,
  plugins: [...entry.plugins, terser({ ...terserOptions, module: true })],
});

// external video.js and its plugins are hashed
function hashPathsPlugin() {
  return {
    name: 'hash-paths',
    outputOptions(options) {
      if (!existsSync(DIST_DIR)) {
        return options;
      }

      options.paths = options.paths || {};
      const fileMappings = {
        'video.js': 'video.es-',
        'videojs-yt-style': 'videojs-yt-style-',
        'videojs-mobile-ui': 'videojs-mobile-ui-',
      };
      const files = readdirSync(DIST_DIR).filter((f) => f.endsWith('.js'));
      for (const [key, prefix] of Object.entries(fileMappings)) {
        const matchingFile = files.find((file) => file.startsWith(prefix));
        if (matchingFile) {
          options.paths[key] = `./${matchingFile}`;
        }
      }
      return options;
    },
  };
}

const withHashPaths = (entry) => ({
  ...entry,
  plugins: [...entry.plugins, hashPathsPlugin()],
});

export default [
  ...videojsEntries.map((entry) => ({
    ...withTerser(entry),
    ...withHashPaths(entry),
    output: {
      dir: `${DIST_DIR}`,
      format: 'es',
      entryFileNames: '[name]-[hash].js',
    },
  })),

  // Main Bundle
  {
    input: PROD_HTML,
    output: {
      dir: DIST_DIR,
      format: 'es',
      sourcemap: true,
      assetFileNames: '[name]-[hash][extname]',
      entryFileNames: '[name]-[hash].js',
      chunkFileNames: '[name]-[hash].js',
    },
    external: ['video.js', 'videojs-yt-style', 'videojs-mobile-ui'],
    plugins: [
      hashPathsPlugin(),
      del({
        // remove previous env.js
        targets: `${DIST_DIR}/env-*.js`,
      }),
      html({
        minify: true,
        minifyCss: true,
        transformHtml: (html) => {
          return (
            html
              // remove importmap
              .replace(/<script type="importmap">[\s\S]*?<\/script>/, '')
              // restore absolute path from html plugin
              .replace(/href="(\w)/g, 'href="/$1')
              .replace(/src="(\w)/g, 'src="/$1')
              .replace(/src="\.\/index-(.*)\.js"/g, 'src="/index-$1.js"')
          );
        },
      }),
      deleteProdHtmlFile(),
      babel({
        babelHelpers: 'bundled',
        exclude: ['**/node_modules/**'],
        plugins: [
          [
            'babel-plugin-htm',
            {
              tag: 'html',
              import: 'htm/preact',
            },
          ],
        ],
      }),
      nodeResolve({
        browser: true,
        extensions: ['.js', '.mjs'],
      }),
      commonjs(),
      css({
        minify: true,
      }),
      terser({
        ...terserOptions,
        module: true,
      }),
    ],
  },

  // Service worker
  {
    input: 'front/videoserviceworker.js',
    output: {
      file: `${DIST_DIR}/videoserviceworker.js`,
      format: 'iife',
    },
    plugins: [
      terser({
        ...terserOptions,
        module: false,
      }),
    ],
  },
];
