FROM alpine:3.21.0

RUN apk add --no-cache \
    make \
    gcc \
    yasm \
    g++

ENV SOURCE_DIR=/sources

ADD third-party/ ${SOURCE_DIR}/

# Build zlib
RUN cd "${SOURCE_DIR}/zlib"  \
    && ./configure --static \
    && make -j -k \
    && make install
# Build libpng
RUN cd "${SOURCE_DIR}/libpng" \
    && ./configure --disable-shared --enable-static \
    && make -j -k \
    && make install
# Build FFmpeg
RUN cd "${SOURCE_DIR}/ffmpeg" \
    && ./configure \
    --enable-version3 \
    --enable-swscale \
    --enable-avformat \
    --enable-avcodec \
    --enable-avutil \
    --disable-protocols \
    --disable-zlib \
    --disable-bzlib \
    --disable-lzma \
    --disable-libdrm \
    --disable-programs \
    --disable-doc \
    --disable-network  \
    && make -j -k \
    && make install

ENV CXXFLAGS="-O3 -I${SOURCE_DIR} -DNDEBUG"
ENV CFLAGS="-O3 -I${SOURCE_DIR} -DNDEBUG -Wno-stringop-overread"
# alpine 3.21.0
# sqlite3.c:35252:28: error: 'strlen' reading 1 or more bytes from a region of size 0 [-Werror=stringop-overread]
#       return 0x3fffffff & (int)strlen(z);

# add local file after building FFmpeg for performance
ADD *.h *.cpp Makefile ${SOURCE_DIR}/
